Update build-module.yml

diff --git a/.github/workflows/build-module.yml b/.github/workflows/build-module.yml
--- a/.github/workflows/build-module.yml
+++ b/.github/workflows/build-module.yml
@@ -186,17 +186,18 @@ jobs:
       - name: Prepare artifacts
         run: |
           # Find SDK directory
-          SDK_DIR=$(find . -maxdepth 1 -name "openwrt-sdk-*" -type d | head -n1)/bin
-          
+          SDK_DIR=$(find . -maxdepth 1 -name "openwrt-sdk-*" -type d | head -n1)
+          REL_DIR=$(pwd)/awgrelease
           mkdir -p awgrelease
+          cd "$SDK_DIR"
           postfix="v${{ matrix.build_env.tag }}_${{ matrix.build_env.pkgarch}}_${{ matrix.build_env.target}}_${{ matrix.build_env.subtarget}}"
           
           # Copy built packages
-          find "$SDK_DIR" -name "amneziawg-tools_*.apk"
-          find "$SDK_DIR" -name "amneziawg-tools_*.apk" -exec cp {} awgrelease/amneziawg-tools_${postfix}.apk \; || echo "amneziawg-tools package not found"
-          find "$SDK_DIR" -name "luci-proto-amneziawg_*.apk" -exec cp {} awgrelease/luci-proto-amneziawg_${postfix}.apk \; || echo "luci-proto-amneziawg package not found"
-          find "$SDK_DIR" -name "luci-i18n-amneziawg-ru_*.apk" -exec cp {} awgrelease/luci-i18n-amneziawg-ru_${postfix}.apk \; || echo "luci-i18n-amneziawg-ru package not found"
-          find "$SDK_DIR" -name "kmod-amneziawg_*.apk" -exec cp {} awgrelease/kmod-amneziawg_${postfix}.apk \; || echo "kmod-amneziawg package not found"
+          find "bin/" -name "amneziawg-tools_*.apk"
+          find "bin/" -name "amneziawg-tools_*.apk" -exec cp {} "$REL_DIR/amneziawg-tools_${postfix}.apk" \; || echo "amneziawg-tools package not found"
+          find "bin/" -name "luci-proto-amneziawg_*.apk" -exec cp {} "$REL_DIR/luci-proto-amneziawg_${postfix}.apk" \; || echo "luci-proto-amneziawg package not found"
+          find "bin/" -name "luci-i18n-amneziawg-ru_*.apk" -exec cp {} "$REL_DIR/luci-i18n-amneziawg-ru_${postfix}.apk" \; || echo "luci-i18n-amneziawg-ru package not found"
+          find "bin/" -name "kmod-amneziawg_*.apk" -exec cp {} "$REL_DIR/kmod-amneziawg_${postfix}.apk" \; || echo "kmod-amneziawg package not found"
           
           echo "Built packages:"
           ls -la awgrelease/
